name: Contrustion d'un build pour shopping-app

on:
  push:
    branches: ["master"]
  workflow_dispatch: #rien de spécial


jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
      - name: Create folder on remote vm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: mkdir -p /home/devops/shopping-app
  build:
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - name: Télechargement des sources
        uses: actions/checkout@v3
      - name: Setup up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -Dmaven.test.skip=true -B package --file pom.xml
      - name: Rename jar
        run: mv target/*.jar target/shopping-app.jar

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "target/shopping-app.jar"
          target: /home/devops/shopping-app

  run script:
    name: run script
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create folder on remote vm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ln -sf  /home/devops/shopping-app/shopping-app.jar  /etc/init.d/shopping-app
            service start shopping-app