name: Contrustion d'un build pour shopping-app

on:
  push:
    branches: ["master"]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Télechargement des sources
        uses: actions/checkout@v3
      - name: Setup up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -Dmaven.test.skip=true -B package --file pom.xml